In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
df=pd.read_csv('/content/USA_Housing.csv')
df

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
0,79545.458574,5.682861,7.009188,4.09,23086.800503,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.642455,6.002900,6.730821,3.09,40173.072174,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.067179,5.865890,8.512727,5.13,36882.159400,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.240046,7.188236,5.586729,3.26,34310.242831,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.197226,5.040555,7.839388,4.23,26354.109472,6.309435e+05,USNS Raymond\nFPO AE 09386
...,...,...,...,...,...,...,...
4995,60567.944140,7.830362,6.137356,3.46,22837.361035,1.060194e+06,USNS Williams\nFPO AP 30153-7653
4996,78491.275435,6.999135,6.576763,4.02,25616.115489,1.482618e+06,"PSC 9258, Box 8489\nAPO AA 42991-3352"
4997,63390.686886,7.250591,4.805081,2.13,33266.145490,1.030730e+06,"4215 Tracy Garden Suite 076\nJoshualand, VA 01..."
4998,68001.331235,5.534388,7.130144,5.44,42625.620156,1.198657e+06,USS Wallace\nFPO AE 73316
4999,65510.581804,5.992305,6.792336,4.07,46501.283803,1.298950e+06,"37778 George Ridges Apt. 509\nEast Holly, NV 2..."

In [6]:
df_a=df.drop(columns=['Address'])

In [7]:
df_a

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
0,79545.458574,5.682861,7.009188,4.09,23086.800503,1.059034e+06
1,79248.642455,6.002900,6.730821,3.09,40173.072174,1.505891e+06
2,61287.067179,5.865890,8.512727,5.13,36882.159400,1.058988e+06
3,63345.240046,7.188236,5.586729,3.26,34310.242831,1.260617e+06
4,59982.197226,5.040555,7.839388,4.23,26354.109472,6.309435e+05
...,...,...,...,...,...,...
4995,60567.944140,7.830362,6.137356,3.46,22837.361035,1.060194e+06
4996,78491.275435,6.999135,6.576763,4.02,25616.115489,1.482618e+06
4997,63390.686886,7.250591,4.805081,2.13,33266.145490,1.030730e+06
4998,68001.331235,5.534388,7.130144,5.44,42625.620156,1.198657e+06
4999,65510.581804,5.992305,6.792336,4.07,46501.283803,1.298950e+06

In [13]:
# Splitting data into features and target variable
X = df[['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
          'Avg. Area Number of Bedrooms', 'Area Population']]
y = df['Price']

In [15]:
from sklearn.model_selection import train_test_split
# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
from sklearn.preprocessing import StandardScaler
# Standardizing the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [17]:
# Implementing KNN Regression from Scratch in normal way
def knn_regression(X_train, y_train, X_test, k=5):
    predictions = []
    for test_point in X_test:
        distances = np.linalg.norm(X_train - test_point, axis=1)
        k_indices = distances.argsort()[:k]
        k_nearest_values = y_train.iloc[k_indices]
        predictions.append(np.mean(k_nearest_values))
    return np.array(predictions)

In [18]:

# Using our custom KNN regressor
predictions_custom = knn_regression(X_train_scaled, y_train, X_test_scaled, k=5)

In [21]:
# Calculating mean squared error for custom KNN
from sklearn.metrics import mean_squared_error
mse_custom = mean_squared_error(y_test, predictions_custom)
mse_custom

16078241760.745293

In [23]:
from sklearn.neighbors import KNeighborsRegressor

# Using sklearn's KNN regressor for comparison
knn_sklearn = KNeighborsRegressor(n_neighbors=5)
knn_sklearn.fit(X_train_scaled, y_train)
predictions_sklearn = knn_sklearn.predict(X_test_scaled)

In [24]:
# Calculating mean squared error for sklearn KNN
mse_sklearn = mean_squared_error(y_test, predictions_sklearn)
mse_sklearn

16078241760.745293

In [25]:
#new data prediction
new_data_point = np.array([[65000, 5, 7, 4, 30000]])  # Example new data point

In [26]:
# Standardizing the new data point
new_data_point_scaled = scaler.transform(new_data_point)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [27]:
new_prediction_custom = knn_regression(X_train_scaled, y_train, new_data_point_scaled, k=5)

In [28]:
new_prediction_sklearn = knn_sklearn.predict(new_data_point_scaled)

In [30]:
new_prediction_sklearn = knn_sklearn.predict(new_data_point_scaled)
new_prediction_sklearn

array([934207.75013953])